/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ConexionBaseDeDatos.ConexionBD;
import ConexionBaseDeDatos.ConexionBD_CatalogoDeMotos;
import static Formularios.frmInClienteNuevo.codigo_direccion;
import static Formularios.frmInClienteNuevo.direccion_completa;
import static Formularios.frmPrincipal.jdpPantallaPrincipal;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author alber
 */
public class frmInCatalogoDeMotosNuevo extends javax.swing.JInternalFrame {
    //VARIABLES GLOBALES    
    //Variables para Alto y Ancho de Formularios Internos
    int alto, ancho;
    //VARIABLES GLOBALES PARA DIRECCION
    public static int codigo_direccion;
    public static String nombre_direccion;
    public static boolean resultadoInstruccion = false;
    
    //VARIABLE GLOBAL PARA DOCUMENTOS
    String nombreArchivo, rutaArchivo;
    FileInputStream foto;
    public frmInCatalogoDeMotosNuevo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRegistroMotosDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRegistroMotosNumeroPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRegistroMotosMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRegistroMotosModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRegistroMotosColor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRegistroMotosMotor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRegistroMotosIdGPS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRegistroMotosChipGPS = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRegistroMotosFoto = new javax.swing.JTextField();
        lblBotonAdjuntarFoto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRegistroMotosAgenciaProveedora = new javax.swing.JTextField();
        lblBotonBuscarAgenciaProveedora = new javax.swing.JLabel();
        lblBotonGuardarRegistroMotos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(134, 185, 22));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRAR NUEVAS MOTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtRegistroMotosDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroMotosDescripcionActionPerformed(evt);
            }
        });

        jLabel2.setText("1. DESCRIPCIÓN:");

        jLabel3.setText("2. NÚMERO DE PLACA:");

        txtRegistroMotosNumeroPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegistroMotosNumeroPlacaKeyTyped(evt);
            }
        });

        jLabel4.setText("3. MARCA:");

        jLabel5.setText("4. MODELO:");

        jLabel6.setText("5. COLOR:");

        jLabel7.setText("6. MOTOR:");

        jLabel8.setText("7. ID DEL GPS:");

        txtRegistroMotosIdGPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegistroMotosIdGPSKeyTyped(evt);
            }
        });

        jLabel9.setText("8. CHIP DEL GPS:");

        txtRegistroMotosChipGPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegistroMotosChipGPSKeyTyped(evt);
            }
        });

        jLabel10.setText("9. FOTO:");

        txtRegistroMotosFoto.setEditable(false);

        lblBotonAdjuntarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_adjunto_20x20.png"))); // NOI18N
        lblBotonAdjuntarFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotonAdjuntarFotoMouseClicked(evt);
            }
        });

        jLabel12.setText("10. AGENCIA PROVEEDORA:");

        txtRegistroMotosAgenciaProveedora.setEditable(false);
        txtRegistroMotosAgenciaProveedora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroMotosAgenciaProveedoraActionPerformed(evt);
            }
        });

        lblBotonBuscarAgenciaProveedora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crud_search_20x20.png"))); // NOI18N
        lblBotonBuscarAgenciaProveedora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotonBuscarAgenciaProveedoraMouseClicked(evt);
            }
        });

        lblBotonGuardarRegistroMotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crud_accept_50x50.png"))); // NOI18N
        lblBotonGuardarRegistroMotos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotonGuardarRegistroMotosMouseClicked(evt);
            }
        });
        lblBotonGuardarRegistroMotos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblBotonGuardarRegistroMotosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtRegistroMotosModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtRegistroMotosColor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2)
                            .addComponent(txtRegistroMotosDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtRegistroMotosNumeroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtRegistroMotosMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(txtRegistroMotosChipGPS, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtRegistroMotosFoto)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblBotonAdjuntarFoto))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(txtRegistroMotosMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(txtRegistroMotosIdGPS, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRegistroMotosAgenciaProveedora, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBotonBuscarAgenciaProveedora))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(lblBotonGuardarRegistroMotos)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegistroMotosDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegistroMotosNumeroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegistroMotosMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegistroMotosModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegistroMotosColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegistroMotosMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegistroMotosIdGPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegistroMotosChipGPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBotonAdjuntarFoto)
                            .addComponent(txtRegistroMotosFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRegistroMotosAgenciaProveedora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBotonBuscarAgenciaProveedora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(lblBotonGuardarRegistroMotos)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegistroMotosDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroMotosDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroMotosDescripcionActionPerformed

    private void txtRegistroMotosAgenciaProveedoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroMotosAgenciaProveedoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroMotosAgenciaProveedoraActionPerformed

    private void lblBotonBuscarAgenciaProveedoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonBuscarAgenciaProveedoraMouseClicked
        // TODO add your handling code here:
        //Abrir el Formulario para Buscar Agencias de Carros
        frmInCatalogoDeMotosBuscarAgencia frmCatalogoDeMotosBuscarAgencia = new frmInCatalogoDeMotosBuscarAgencia();
        ancho = (jdpPantallaPrincipal.getWidth()/2) - frmCatalogoDeMotosBuscarAgencia.getWidth()/2;
        alto = (jdpPantallaPrincipal.getHeight()/2) - frmCatalogoDeMotosBuscarAgencia.getHeight()/2;
        frmInCatalogoDeMotosBuscarAgencia.comparador = false;
        jdpPantallaPrincipal.add(frmCatalogoDeMotosBuscarAgencia);
        frmCatalogoDeMotosBuscarAgencia.setLocation(ancho, alto);
        frmCatalogoDeMotosBuscarAgencia.show();
    }//GEN-LAST:event_lblBotonBuscarAgenciaProveedoraMouseClicked
  
    private void lblBotonGuardarRegistroMotosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblBotonGuardarRegistroMotosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBotonGuardarRegistroMotosKeyTyped

    private void lblBotonGuardarRegistroMotosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonGuardarRegistroMotosMouseClicked
       //REALIZA LA VALIDACION DE CAMPOS VACIOS 
        if(txtRegistroMotosDescripcion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Descripcion");
        }else if (txtRegistroMotosNumeroPlaca.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Numero de Placa");
        }else if (txtRegistroMotosMarca.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Marca");
        }else if (txtRegistroMotosModelo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Modelo");
        }else if (txtRegistroMotosColor.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Color");
        }else if (txtRegistroMotosMotor.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Motor");
        }else if (txtRegistroMotosIdGPS.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Id del GPS");
        }else if (txtRegistroMotosChipGPS.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Chip del GPS");
        }else if (txtRegistroMotosFoto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Foto");
        }else if (txtRegistroMotosAgenciaProveedora.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Agencia Proveedora");
        } else{
             //PREPARAR ARCHIVO PARA BASE DE DATOS SI EXISTE UNO
        if(txtRegistroMotosFoto.getText().equals("")){
            foto = null;
        }else{
            File file = new File(rutaArchivo);
            try {
                foto = new FileInputStream(file);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(frmInClienteNuevo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                String descripcion = txtRegistroMotosDescripcion.getText();
                String numero_placa = txtRegistroMotosNumeroPlaca.getText();
                String marca = txtRegistroMotosMarca.getText();
                String modelo = txtRegistroMotosModelo.getText();
                String color = txtRegistroMotosColor.getText();
                String motor = txtRegistroMotosMotor.getText();
                String id_gps = txtRegistroMotosIdGPS.getText();
                String chip_gps = txtRegistroMotosChipGPS.getText();               
                String agencia_proveedora = txtRegistroMotosAgenciaProveedora.getText();
                
                ConexionBD.Iniciar();
                resultadoInstruccion = ConexionBD_CatalogoDeMotos.ingresarMotos("VIGENTE", "MOTO", descripcion, numero_placa, marca, modelo, color, motor, id_gps, chip_gps, foto);
                int cod_vehiculo = ConexionBD_CatalogoDeMotos.obtenerUltimaMotoIngresada();
                ConexionBD_CatalogoDeMotos.ingresarVehiculoAgencia(cod_vehiculo, codigo_direccion);
                ConexionBD.Finalizar();
                //SE VERIFICA SI SE REALIZÓ EL INGRESO DE DATOS
        if(resultadoInstruccion == true){
            JOptionPane.showMessageDialog(null, "DATOS INGRESADOS ÉXITOSAMENTE");
            
            //LIMPIEZA DE CAMPOS
            vaciarCampos();

            //LIMPIEZA DE VARIABLES GLOBALES
            resultadoInstruccion = false;
            codigo_direccion = 0;
            direccion_completa = null;
            nombreArchivo = null;
            rutaArchivo = null;
            foto = null;
        }else{
            JOptionPane.showMessageDialog(null, "HUBO UN ERROR AL INGRESAR LOS DATOS");
        }
        }
    }//GEN-LAST:event_lblBotonGuardarRegistroMotosMouseClicked

    private void txtRegistroMotosNumeroPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegistroMotosNumeroPlacaKeyTyped
        noEspacios(evt);
    }//GEN-LAST:event_txtRegistroMotosNumeroPlacaKeyTyped

    private void txtRegistroMotosIdGPSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegistroMotosIdGPSKeyTyped
        noEspacios(evt);
    }//GEN-LAST:event_txtRegistroMotosIdGPSKeyTyped

    private void txtRegistroMotosChipGPSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegistroMotosChipGPSKeyTyped
        noEspacios(evt);
    }//GEN-LAST:event_txtRegistroMotosChipGPSKeyTyped

    private void lblBotonAdjuntarFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonAdjuntarFotoMouseClicked
        //SE SELECCIONA EL ARCHIVO A SUBIR
        JFileChooser archivoSeleccionado = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos JPG, PNG", "jpg", "png");
        archivoSeleccionado.setFileFilter(filtro);
        int opcion = archivoSeleccionado.showOpenDialog(this);
        
        if(opcion == JFileChooser.APPROVE_OPTION){
            nombreArchivo = archivoSeleccionado.getSelectedFile().getName();
            rutaArchivo = archivoSeleccionado.getSelectedFile().getPath();
            
            txtRegistroMotosFoto.setText(nombreArchivo);
        }
    }//GEN-LAST:event_lblBotonAdjuntarFotoMouseClicked
    //VARIABLE AUXILIAR QUE ALMACENARA EL CARACTER INGRESADO
    Character simbolo;
    private void noEspacios (KeyEvent evt){
        //SE ALMACENA EL CARACTER
        simbolo = evt.getKeyChar();
        //SE COMPARA SI ES UN ESPACIO EN BLANCO
        if (simbolo == KeyEvent.VK_SPACE){
            //SI ES ASI SE CONSUME Y DESAPARECE EL VALOR, DEVOLVIENDO COMO QUE NO SE HUBIERA PRESIONADO NADA
            evt.consume();
        }
    }
            private void vaciarCampos(){
              txtRegistroMotosDescripcion.setText("");
              txtRegistroMotosNumeroPlaca.setText("");
              txtRegistroMotosMarca.setText("");
              txtRegistroMotosModelo.setText("");
              txtRegistroMotosColor.setText("");
              txtRegistroMotosMotor.setText("");
              txtRegistroMotosIdGPS.setText("");
              txtRegistroMotosChipGPS.setText(""); 
              txtRegistroMotosFoto.setText("");
              txtRegistroMotosAgenciaProveedora.setText("");  
            }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBotonAdjuntarFoto;
    private javax.swing.JLabel lblBotonBuscarAgenciaProveedora;
    private javax.swing.JLabel lblBotonGuardarRegistroMotos;
    public static javax.swing.JTextField txtRegistroMotosAgenciaProveedora;
    private javax.swing.JTextField txtRegistroMotosChipGPS;
    private javax.swing.JTextField txtRegistroMotosColor;
    private javax.swing.JTextField txtRegistroMotosDescripcion;
    private javax.swing.JTextField txtRegistroMotosFoto;
    private javax.swing.JTextField txtRegistroMotosIdGPS;
    private javax.swing.JTextField txtRegistroMotosMarca;
    private javax.swing.JTextField txtRegistroMotosModelo;
    private javax.swing.JTextField txtRegistroMotosMotor;
    private javax.swing.JTextField txtRegistroMotosNumeroPlaca;
    // End of variables declaration//GEN-END:variables
}
