/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ClassCatalogoMotos_LlenarTabla;
import ConexionBaseDeDatos.ConexionBD;
import ConexionBaseDeDatos.ConexionBD_CatalogoDeMotos;
import static Formularios.frmInCatalogoDeMotos.tbCatalogoDeMotos;
import static Formularios.frmInClienteNuevo.codigo_direccion;
import static Formularios.frmInClienteNuevo.direccion_completa;
import static Formularios.frmPrincipal.jdpPantallaPrincipal;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alber
 */
public class frmInCatalogoDeMotosNuevo extends javax.swing.JInternalFrame {
    //VARIABLES GLOBALES    
    //Variables para Alto y Ancho de Formularios Internos
    int alto, ancho;
    //VARIABLES GLOBALES PARA DIRECCION
    public static int codigo_direccion;
    public static String nombre_direccion;
    public static boolean resultadoInstruccion = false;
    
    //VARIABLE GLOBAL PARA DOCUMENTOS
    String nombreArchivo, rutaArchivo;
    FileInputStream foto;
    public frmInCatalogoDeMotosNuevo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRegistroMotosDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRegistroMotosNumeroPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRegistroMotosMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRegistroMotosModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRegistroMotosColor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRegistroMotosMotor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRegistroMotosIdGPS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRegistroMotosChipGPS = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRegistroMotosFoto = new javax.swing.JTextField();
        lblBotonAdjuntarFoto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRegistroMotosAgenciaProveedora = new javax.swing.JTextField();
        lblBotonBuscarAgenciaProveedora = new javax.swing.JLabel();
        lblBotonGuardarRegistroMotos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Finanssoreal.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(134, 185, 22));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRAR NUEVAS MOTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        txtRegistroMotosDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroMotosDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(txtRegistroMotosDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 300, -1));

        jLabel2.setText("1. DESCRIPCIÓN:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel3.setText("2. NÚMERO DE PLACA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 158, -1, -1));

        txtRegistroMotosNumeroPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegistroMotosNumeroPlacaKeyTyped(evt);
            }
        });
        getContentPane().add(txtRegistroMotosNumeroPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 178, 140, -1));

        jLabel4.setText("3. MARCA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 158, -1, -1));
        getContentPane().add(txtRegistroMotosMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 178, 140, -1));

        jLabel5.setText("4. MODELO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 216, -1, -1));
        getContentPane().add(txtRegistroMotosModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 236, 140, -1));

        jLabel6.setText("5. COLOR:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 216, -1, -1));
        getContentPane().add(txtRegistroMotosColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 236, 140, -1));

        jLabel7.setText("6. MOTOR:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 274, -1, -1));
        getContentPane().add(txtRegistroMotosMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 294, 140, -1));

        jLabel8.setText("7. ID DEL GPS:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 274, -1, -1));

        txtRegistroMotosIdGPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegistroMotosIdGPSKeyTyped(evt);
            }
        });
        getContentPane().add(txtRegistroMotosIdGPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 294, 140, -1));

        jLabel9.setText("8. CHIP DEL GPS:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 332, -1, -1));

        txtRegistroMotosChipGPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegistroMotosChipGPSKeyTyped(evt);
            }
        });
        getContentPane().add(txtRegistroMotosChipGPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 352, 140, -1));

        jLabel10.setText("9. FOTO:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 332, -1, -1));

        txtRegistroMotosFoto.setEditable(false);
        getContentPane().add(txtRegistroMotosFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 352, 116, -1));

        lblBotonAdjuntarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_adjunto_20x20.png"))); // NOI18N
        lblBotonAdjuntarFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotonAdjuntarFotoMouseClicked(evt);
            }
        });
        getContentPane().add(lblBotonAdjuntarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 352, -1, -1));

        jLabel12.setText("10. AGENCIA PROVEEDORA:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        txtRegistroMotosAgenciaProveedora.setEditable(false);
        txtRegistroMotosAgenciaProveedora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroMotosAgenciaProveedoraActionPerformed(evt);
            }
        });
        getContentPane().add(txtRegistroMotosAgenciaProveedora, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 273, -1));

        lblBotonBuscarAgenciaProveedora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crud_search_20x20.png"))); // NOI18N
        lblBotonBuscarAgenciaProveedora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotonBuscarAgenciaProveedoraMouseClicked(evt);
            }
        });
        getContentPane().add(lblBotonBuscarAgenciaProveedora, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 410, -1, -1));

        lblBotonGuardarRegistroMotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crud_accept_50x50.png"))); // NOI18N
        lblBotonGuardarRegistroMotos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotonGuardarRegistroMotosMouseClicked(evt);
            }
        });
        lblBotonGuardarRegistroMotos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblBotonGuardarRegistroMotosKeyTyped(evt);
            }
        });
        getContentPane().add(lblBotonGuardarRegistroMotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegistroMotosDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroMotosDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroMotosDescripcionActionPerformed

    private void txtRegistroMotosAgenciaProveedoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroMotosAgenciaProveedoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroMotosAgenciaProveedoraActionPerformed

    private void lblBotonBuscarAgenciaProveedoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonBuscarAgenciaProveedoraMouseClicked
        // TODO add your handling code here:
        //Abrir el Formulario para Buscar Agencias de Carros
        frmInCatalogoDeMotosBuscarAgencia frmCatalogoDeMotosBuscarAgencia = new frmInCatalogoDeMotosBuscarAgencia();
        ancho = (jdpPantallaPrincipal.getWidth()/2) - frmCatalogoDeMotosBuscarAgencia.getWidth()/2;
        alto = (jdpPantallaPrincipal.getHeight()/2) - frmCatalogoDeMotosBuscarAgencia.getHeight()/2;
        frmInCatalogoDeMotosBuscarAgencia.comparador = false;
        jdpPantallaPrincipal.add(frmCatalogoDeMotosBuscarAgencia);
        frmCatalogoDeMotosBuscarAgencia.setLocation(ancho, alto);
        frmCatalogoDeMotosBuscarAgencia.show();
    }//GEN-LAST:event_lblBotonBuscarAgenciaProveedoraMouseClicked
  
    private void lblBotonGuardarRegistroMotosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblBotonGuardarRegistroMotosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBotonGuardarRegistroMotosKeyTyped

    private void lblBotonGuardarRegistroMotosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonGuardarRegistroMotosMouseClicked
       //REALIZA LA VALIDACION DE CAMPOS VACIOS 
        if(txtRegistroMotosDescripcion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Descripcion");
        }else if (txtRegistroMotosNumeroPlaca.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Numero de Placa");
        }else if (txtRegistroMotosMarca.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Marca");
        }else if (txtRegistroMotosModelo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Modelo");
        }else if (txtRegistroMotosColor.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Color");
        }else if (txtRegistroMotosMotor.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Motor");
        }else if (txtRegistroMotosIdGPS.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Id del GPS");
        }else if (txtRegistroMotosChipGPS.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Chip del GPS");
        }else if (txtRegistroMotosFoto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Foto");
        }else if (txtRegistroMotosAgenciaProveedora.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacio: Agencia Proveedora");
        } else{
             //PREPARAR ARCHIVO PARA BASE DE DATOS SI EXISTE UNO
        if(txtRegistroMotosFoto.getText().equals("")){
            foto = null;
        }else{
            File file = new File(rutaArchivo);
            try {
                foto = new FileInputStream(file);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(frmInClienteNuevo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                String descripcion = txtRegistroMotosDescripcion.getText();
                String numero_placa = txtRegistroMotosNumeroPlaca.getText();
                String marca = txtRegistroMotosMarca.getText();
                String modelo = txtRegistroMotosModelo.getText();
                String color = txtRegistroMotosColor.getText();
                String motor = txtRegistroMotosMotor.getText();
                String id_gps = txtRegistroMotosIdGPS.getText();
                String chip_gps = txtRegistroMotosChipGPS.getText();               
                String agencia_proveedora = txtRegistroMotosAgenciaProveedora.getText();
                
                ConexionBD.Iniciar();
                resultadoInstruccion = ConexionBD_CatalogoDeMotos.ingresarMotos("VIGENTE", "MOTO", descripcion, numero_placa, marca, modelo, color, motor, id_gps, chip_gps, foto);
                int cod_vehiculo = ConexionBD_CatalogoDeMotos.obtenerUltimaMotoIngresada();
                ConexionBD_CatalogoDeMotos.ingresarVehiculoAgencia(cod_vehiculo, codigo_direccion);
                ConexionBD.Finalizar();
                //SE VERIFICA SI SE REALIZÓ EL INGRESO DE DATOS
        if(resultadoInstruccion == true){
            JOptionPane.showMessageDialog(null, "DATOS INGRESADOS ÉXITOSAMENTE");
            
            //LIMPIEZA DE CAMPOS
            vaciarCampos();

            //LIMPIEZA DE VARIABLES GLOBALES
            resultadoInstruccion = false;
            codigo_direccion = 0;
            direccion_completa = null;
            nombreArchivo = null;
            rutaArchivo = null;
            foto = null;
            
            //ACTUALIZA LA TABLA PRINCIPAL
            ConexionBaseDeDatos.ConexionBD.Iniciar();
            actualizarTablaCatalogoMotos(ConexionBaseDeDatos.ConexionBD_CatalogoDeMotos.mostrarTodoCatalogoDeMotos());
            ConexionBaseDeDatos.ConexionBD.Finalizar();
        }else{
            JOptionPane.showMessageDialog(null, "HUBO UN ERROR AL INGRESAR LOS DATOS");
        }
        }
    }//GEN-LAST:event_lblBotonGuardarRegistroMotosMouseClicked

    private void txtRegistroMotosNumeroPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegistroMotosNumeroPlacaKeyTyped
        noEspacios(evt);
    }//GEN-LAST:event_txtRegistroMotosNumeroPlacaKeyTyped

    private void txtRegistroMotosIdGPSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegistroMotosIdGPSKeyTyped
        noEspacios(evt);
    }//GEN-LAST:event_txtRegistroMotosIdGPSKeyTyped

    private void txtRegistroMotosChipGPSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegistroMotosChipGPSKeyTyped
        noEspacios(evt);
    }//GEN-LAST:event_txtRegistroMotosChipGPSKeyTyped

    private void lblBotonAdjuntarFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonAdjuntarFotoMouseClicked
        //SE SELECCIONA EL ARCHIVO A SUBIR
        JFileChooser archivoSeleccionado = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos JPG, PNG", "jpg", "png");
        archivoSeleccionado.setFileFilter(filtro);
        int opcion = archivoSeleccionado.showOpenDialog(this);
        
        if(opcion == JFileChooser.APPROVE_OPTION){
            nombreArchivo = archivoSeleccionado.getSelectedFile().getName();
            rutaArchivo = archivoSeleccionado.getSelectedFile().getPath();
            
            txtRegistroMotosFoto.setText(nombreArchivo);
        }
    }//GEN-LAST:event_lblBotonAdjuntarFotoMouseClicked
    //VARIABLE AUXILIAR QUE ALMACENARA EL CARACTER INGRESADO
    Character simbolo;
    private void noEspacios (KeyEvent evt){
        //SE ALMACENA EL CARACTER
        simbolo = evt.getKeyChar();
        //SE COMPARA SI ES UN ESPACIO EN BLANCO
        if (simbolo == KeyEvent.VK_SPACE){
            //SI ES ASI SE CONSUME Y DESAPARECE EL VALOR, DEVOLVIENDO COMO QUE NO SE HUBIERA PRESIONADO NADA
            evt.consume();
        }
    }
    private void vaciarCampos(){
        txtRegistroMotosDescripcion.setText("");
        txtRegistroMotosNumeroPlaca.setText("");
        txtRegistroMotosMarca.setText("");
        txtRegistroMotosModelo.setText("");
        txtRegistroMotosColor.setText("");
        txtRegistroMotosMotor.setText("");
        txtRegistroMotosIdGPS.setText("");
        txtRegistroMotosChipGPS.setText(""); 
        txtRegistroMotosFoto.setText("");
        txtRegistroMotosAgenciaProveedora.setText("");  
    }
    
    void actualizarTablaCatalogoMotos(ResultSet estructuraTabla) {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            //Primero se Definen las Columnas
            modelo.addColumn("CÓDIGO");         
            modelo.addColumn("DESCRIPCIÓN");
            modelo.addColumn("MARCA");
            modelo.addColumn("MODELO");
            modelo.addColumn("AGENCIA PROVEEDORA");
            
            //se definen los tamaÃ±os de las columnas
            frmInCatalogoDeMotos.tbCatalogoDeMotos.setModel(modelo);
            
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(0).setPreferredWidth(275);
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(0).setMaxWidth(300);
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(0).setMinWidth(5);
            
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(1).setPreferredWidth(550);
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(1).setMaxWidth(600);
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(1).setMinWidth(5);
            
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(2).setPreferredWidth(300);
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(2).setMaxWidth(520);
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(2).setMinWidth(5);
            
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(3).setPreferredWidth(550);
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(3).setMaxWidth(600);
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(3).setMinWidth(5);       
            
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(4).setPreferredWidth(550);
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(4).setMaxWidth(600);
            frmInCatalogoDeMotos.tbCatalogoDeMotos.getColumnModel().getColumn(4).setMinWidth(5);  
            //se usa un while ya que se va a recorrer fila por fila lo que se obtuvo de la BD.
            while (estructuraTabla.next()) { 
                
                //se obtienen los datos de la base de datos mediante el uso del constructor de la clase correspondiente
                ClassCatalogoMotos_LlenarTabla person = new ClassCatalogoMotos_LlenarTabla( //se instancia un objeto de la clase correspondiente para llenar la tabla mediante un while
                        estructuraTabla.getInt("codigo"),
                        estructuraTabla.getString("descripción"),
                        estructuraTabla.getString("marca"),
                        estructuraTabla.getString("modelo"), 
                        estructuraTabla.getString("agencia_proveedora"));
            
                // se aÃ±ade el registro encontrado al modelo de la tabla
                modelo.addRow(new Object[]{
                   
                    person.getCodigo(),
                    person.getDescripcion(),                   
                    person.getMarca(),
                    person.getModelo(),
                    person.getAgencia_proveedora(),
                    });
            }

            //se muestra todo en la tabla
            frmInCatalogoDeMotos.tbCatalogoDeMotos.setModel(modelo);

        } catch (SQLException ex) {
            Logger.getLogger(ConexionBaseDeDatos.ConexionBD.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Parece que Hubo un error al cargar la tabla: " + ex);
        }
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBotonAdjuntarFoto;
    private javax.swing.JLabel lblBotonBuscarAgenciaProveedora;
    private javax.swing.JLabel lblBotonGuardarRegistroMotos;
    public static javax.swing.JTextField txtRegistroMotosAgenciaProveedora;
    private javax.swing.JTextField txtRegistroMotosChipGPS;
    private javax.swing.JTextField txtRegistroMotosColor;
    private javax.swing.JTextField txtRegistroMotosDescripcion;
    private javax.swing.JTextField txtRegistroMotosFoto;
    private javax.swing.JTextField txtRegistroMotosIdGPS;
    private javax.swing.JTextField txtRegistroMotosMarca;
    private javax.swing.JTextField txtRegistroMotosModelo;
    private javax.swing.JTextField txtRegistroMotosMotor;
    private javax.swing.JTextField txtRegistroMotosNumeroPlaca;
    // End of variables declaration//GEN-END:variables
}
