/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clases.ClassBuscarDireccion;
import Clases.ConexionBD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Martin Rosales
 */
public class frmInAgenciasBuscarDireccion extends javax.swing.JInternalFrame {
    //COMPARA EL FORMULARIO DEL CUAL SE ACCEDIO
    public static boolean comparador;
    /** Creates new form frmInAgenciasBuscarDireccion */
    public frmInAgenciasBuscarDireccion() {
        initComponents();
        
        //CAMBIA EL COLOR DEL TITLE BAR A BLANCO
        //DESPLIUEGA EL FRAME EN EL CENTRO DE LA PANTALLA
                this.setLocation ((frmPrincipal.jdpPantallaPrincipal.getWidth () - this.getWidth ()) / 2,(frmPrincipal.jdpPantallaPrincipal.getHeight () - this.getHeight ()) / 2);
        //INICIA LA CONEXION A LA BD
                ConexionBD.Iniciar();
        //REALIZA ACCIONES DENTRO DE LA BD
                mostrarDatos(ConexionBD.mostrarTodoDireccion());
        //FINALIZA LA CONEXION A LA BD
                ConexionBD.Finalizar();
    }
        //DEFINE LAS VARIABLES PARA COPIAR EL CODIGO Y DIRECCION, HACIENDOLAS ACCESIBLES DESDE CUALQUIER CLASE
        public static int codigo;
        public static String bcf ="";
        public static String muni ="";
        public static String dep ="";
        public static String direccion = "";
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFiltradoInformacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDireccionAgencias = new javax.swing.JTable();
        lblAceptarBusqueda = new javax.swing.JLabel();
        lblBusqueda = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblBotonMoverInicio = new javax.swing.JLabel();
        lblBotonMoverAtras = new javax.swing.JLabel();
        lblBotonMoverAdelante = new javax.swing.JLabel();
        lblBotonMoverFinal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(750, 605));
        setPreferredSize(new java.awt.Dimension(750, 605));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(134, 185, 22));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("BUSCAR DIRECCION DE AGENCIAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setText("FILTRADO DE INFORMACION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        txtFiltradoInformacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltradoInformacionKeyReleased(evt);
            }
        });
        getContentPane().add(txtFiltradoInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 410, -1));

        tbDireccionAgencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDireccionAgencias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 570, 130));

        lblAceptarBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crud_accept_25x25.png"))); // NOI18N
        lblAceptarBusqueda.setText("ACEPTAR");
        lblAceptarBusqueda.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblAceptarBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAceptarBusquedaMouseClicked(evt);
            }
        });
        getContentPane().add(lblAceptarBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        lblBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crud_search_20x20.png"))); // NOI18N
        getContentPane().add(lblBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 173, 190, 10));

        lblBotonMoverInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crud_paginacion_limit_left_64x64.png"))); // NOI18N
        getContentPane().add(lblBotonMoverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        lblBotonMoverAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crud_paginacion_nolimit_left_50x50.png"))); // NOI18N
        getContentPane().add(lblBotonMoverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        lblBotonMoverAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crud_paginacion_nolimit_right_50x50.png"))); // NOI18N
        getContentPane().add(lblBotonMoverAdelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        lblBotonMoverFinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crud_paginacion_limit_right_64x64.png"))); // NOI18N
        getContentPane().add(lblBotonMoverFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

    }//GEN-LAST:event_formInternalFrameOpened

    private void txtFiltradoInformacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltradoInformacionKeyReleased
        // FILTRO PARA BUSQUEDA DENTRO DE LA  TABLA
        //SE CREA UNA VARIABLE DE TIPO DEFAULTABLEMODEL
        DefaultTableModel busquedaDireccion;

        //SE TRASLADAN LOS PARÁMETROS DEL JTABLE A LA DEFAULTMODELTABLE
        busquedaDireccion = (DefaultTableModel) tbDireccionAgencias.getModel();

        //SE GENERA UN TABLEROWSORTER Y SE AGREGA  NUESTRA TABLA
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(busquedaDireccion);
        tbDireccionAgencias.setRowSorter(tr);

        //SE FILTRAN LOS DATOS DE ACUERDO A LOS PARÁMETROS INGRESADOS EN EL TXT
        tr.setRowFilter(RowFilter.regexFilter(txtFiltradoInformacion.getText().toUpperCase()));
    }//GEN-LAST:event_txtFiltradoInformacionKeyReleased

    private void lblAceptarBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAceptarBusquedaMouseClicked
       // TOMAR LOS DATOS SELECCIONADOS
        for(int i=0; i<tbDireccionAgencias.getRowCount(); i++){
            if(tbDireccionAgencias.isRowSelected(i)){
                codigo = (int) tbDireccionAgencias.getValueAt(i, 0);
                direccion = tbDireccionAgencias.getValueAt(i, 1).toString();
                //DETERMINA QUE FORMULARIO DESPLEGO ESTE INTERNAL FRAME
                if(comparador==false){
                    //SE MANDAN LOS DATOS SELECCIONADOS A NUEVO
                frmInAgenciasNuevo.codigo_direccion = codigo;
                frmInAgenciasNuevo.nombre_direccion = direccion;
                frmInAgenciasNuevo.txtDireccion.setText(direccion);
                }else if(comparador==true){
                    //SE MANDAN LOS DATOS SELECCIONADOS A INFO
                frmInAgenciasInfo.codigo_direccion = codigo;
                frmInAgenciasInfo.nombre_direccion = direccion;
                frmInAgenciasInfo.txtDireccion.setText(direccion);
                }
                dispose();
                return;
            }
        }
    }//GEN-LAST:event_lblAceptarBusquedaMouseClicked
     
    //FUNCIÓN PARA MOSTRAR DATOS
    private void mostrarDatos(ResultSet estructuraTabla) {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            //Primero se Definen las Columnas
            modelo.addColumn("CÓDIGO");           
            modelo.addColumn("DIRECCIÓN");
            
            
            //se definen los tamaños de las columnas
            tbDireccionAgencias.setModel(modelo);
            
            tbDireccionAgencias.getColumnModel().getColumn(0).setPreferredWidth(70);
            tbDireccionAgencias.getColumnModel().getColumn(0).setMaxWidth(90);
            tbDireccionAgencias.getColumnModel().getColumn(0).setMinWidth(5);
            
            tbDireccionAgencias.getColumnModel().getColumn(1).setPreferredWidth(450);
            tbDireccionAgencias.getColumnModel().getColumn(1).setMaxWidth(450);
            tbDireccionAgencias.getColumnModel().getColumn(1).setMinWidth(5);
            
                     
            //se usa un while ya que se va a recorrer fila por fila lo que se obtuvo de la BD.
            while (estructuraTabla.next()) { 
                
                //se obtienen los datos de la base de datos mediante el uso del constructor de la clase correspondiente
                ClassBuscarDireccion direccion = new ClassBuscarDireccion( //se instancia un objeto de la clase correspondiente para llenar la tabla mediante un while
                        estructuraTabla.getInt("codigo"),                        
                        estructuraTabla.getString("direccion"));
                

                // se añade el registro encontrado al modelo de la tabla
                modelo.addRow(new Object[]{direccion.getCodigo(),                   
                    direccion.getNombre_direccion()});
            }

            //se muestra todo en la tabla
            tbDireccionAgencias.setModel(modelo);

        } catch (SQLException ex) {
            Logger.getLogger(ConexionBD.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Parece que Hubo un error al cargar la tabla: " + ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAceptarBusqueda;
    private javax.swing.JLabel lblBotonMoverAdelante;
    private javax.swing.JLabel lblBotonMoverAtras;
    private javax.swing.JLabel lblBotonMoverFinal;
    private javax.swing.JLabel lblBotonMoverInicio;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JTable tbDireccionAgencias;
    private javax.swing.JTextField txtFiltradoInformacion;
    // End of variables declaration//GEN-END:variables

}
